name: Gradle Build and Artifact Upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Make Gradle Wrapper executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    - name: Find and Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          **/build/libs/*.jar
        if-no-files-found: error
